<?php

namespace App\Collections\BpTypes;

use Illuminate\Support\Collection;

class BpTypeCollection extends Collection
{

    public function __construct($items)
    {
        parent::__construct(collect($items)->map(function ($data) {
            return new BpTypeColumn($data);
        })->toArray());
    }

    /**
     * @return BpTypeColumn[]
     * */
    public function all()
    {
        return parent::all();
    }

    /**
     * @return BpTypeColumn
     * */
    public function get($key, $default = null)
    {
        return parent::get($key, $default); // TODO: Change the autogenerated stub
    }

    /**
     * @return BpTypeColumn
     * */
    public function random($number = null)
    {
        return parent::random($number);
    }

    /**
     * @param callable|null $callback
     * @param null $default
     * @return BpTypeColumn
     * */
    public function first(callable $callback = null, $default = null)
    {
        $row = parent::first($callback, $default);
        return !is_null($row) ? $row : new BpTypeColumn();
    }
}
