psql -c "\copy mscountry FROM 'csv_backup/country.csv' delimiter ',' csv header;" "host=localhost port=5432 dbname=ventes user=postgres password=revan1853"
psql -c "\copy msprovince FROM 'csv_backup/province.csv' delimiter ',' csv header;" "host=localhost port=5432 dbname=ventes user=postgres password=revan1853"
psql -c "\copy mscity FROM 'csv_backup/city.csv' delimiter ',' csv header;" "host=localhost port=5432 dbname=ventes user=postgres password=revan1853"
psql -c "\copy mssubdistrict FROM 'csv_backup/subdistrict.csv' delimiter ',' csv header;" "host=localhost port=5432 dbname=ventes user=postgres password=revan1853"
psql -c "\copy msvillage FROM 'csv_backup/village.csv' delimiter ',' csv header;" "host=localhost port=5432 dbname=ventes user=postgres password=revan1853"

psql -c "\copy msmenu FROM 'permission/menu.csv' delimiter ',' csv header;" "host=10.21.1.30 port=5432 dbname=ventes user=postgres password=revan1853"
psql -c "\copy msfeature FROM 'permission/feature.csv' delimiter ',' csv header;" "host=10.21.1.30 port=5432 dbname=ventes user=postgres password=revan1853"
psql -c "\copy mspermission FROM 'permission/permission.csv' delimiter ',' csv header;" "host=10.21.1.30 port=5432 dbname=ventes user=postgres password=revan1853"

@REM psql -c "\copy dspbybp FROM 'dsp/dspbybp.csv' delimiter ',' csv header;" "host=10.21.1.30 port=5432 dbname=ventes user=postgres password=revan1853"
@REM psql -c "\copy dspbycust FROM 'dsp/dspbycust.csv' delimiter ',' csv header;" "host=10.21.1.30 port=5432 dbname=ventes user=postgres password=revan1853"
@REM psql -c "\copy dspbycustlabel FROM 'dsp/dspbycustlabel.csv' delimiter ',' csv header;" "host=10.21.1.30 port=5432 dbname=ventes user=postgres password=revan1853"
@REM psql -c "\copy dspbyowner FROM 'dsp/dspbyowner.csv' delimiter ',' csv header;" "host=10.21.1.30 port=5432 dbname=ventes user=postgres password=revan1853"
@REM psql -c "\copy dspbystage FROM 'dsp/dspbystage.csv' delimiter ',' csv header;" "host=10.21.1.30 port=5432 dbname=ventes user=postgres password=revan1853"
@REM psql -c "\copy dspbystatus FROM 'dsp/dspbystatus.csv' delimiter ',' csv header;" "host=10.21.1.30 port=5432 dbname=ventes user=postgres password=revan1853"