<?php

namespace App\Collections\Files;

use Illuminate\Support\Collection;

class FileCollection extends Collection
{

   public function __construct($items)
   {
      parent::__construct(collect($items)->map(function ($data) {
         return new FileColumn($data);
      })->toArray());
   }

   /**
    * @return FileColumn[]
    * */
   public function all()
   {
      return parent::all();
   }

   /**
    * @return FileColumn
    * */
   public function get($key, $default = null)
   {
      return parent::get($key, $default); // TODO: Change the autogenerated stub
   }

   /**
    * @param callable|null $callback
    * @param null $default
    * @return FileColumn
    * */
   public function first(callable $callback = null, $default = null)
   {
      $row = parent::first($callback, $default);
      return !is_null($row) ? $row : new FileColumn();
   }
}
