<?php

namespace App\Collections\BusinessPartner;

use Illuminate\Support\Collection;

class BusinessPartnerCollection extends Collection
{

    public function __construct($items)
    {
        parent::__construct(collect($items)->map(function($data) {
            return new BusinessPartnerColumn($data);
        })->toArray());
    }

    /**
     * @return BusinessPartnerColumn[]
     * */
    public function all()
    {
        return parent::all();
    }

    /**
     * @return BusinessPartnerColumn
     * */
    public function get($key, $default = null)
    {
        return parent::get($key, $default); // TODO: Change the autogenerated stub
    }

    /**
     * @return BusinessPartnerColumn
     * */
    public function random($number = null)
    {
        return parent::random($number);
    }

    /**
     * @param callable|null $callback
     * @param null $default
     * @return BusinessPartnerColumn
     * */
    public function first(callable $callback = null, $default = null)
    {
        $row = parent::first($callback, $default);
        return !is_null($row) ? $row : new BusinessPartnerColumn();
    }
}
